### ISSUE TITLE
Dorado crashed with a compression error

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#376]
My dorado 0.3.2 crashed with a compression error in the middle of a run.
I checked the sha sum of all fast5 in the directory and they matches the values in sha512.txt.
Does that mean one of the files is already corrupted straight out of the sequencer?
If yes, how do I know this is the case?
If no, how do I know the reason for this compression error?

```
ERROR ~ Error executing process > 'basecalling:wf_dorado:dorado (40)'

Caused by:
  Process `basecalling:wf_dorado:dorado (40)` terminated with an error exit status (1)

Command executed:

  set +e
  source /opt/nvidia/entrypoint.d/*-gpu-driver-check.sh # runtime driver check msg
  set -e
  dorado basecaller         ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 .         --modified-bases-models ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2         --verbose         --device cuda:all | samtools view --no-PG -b -o 39.ubam -

Command exit status:
  1

Command output:
  (empty)

Command error:
  [2023-09-18 05:22:14.146] [debug] Auto batch size: testing up to 768 in steps of 64
  [2023-09-18 05:22:14.463] [debug] Auto batchsize: 64, time per chunk 4.958735 ms
  [2023-09-18 05:22:14.556] [debug] Auto batchsize: 128, time per chunk 0.703032 ms
  [2023-09-18 05:22:14.649] [debug] Auto batchsize: 192, time per chunk 0.472224 ms
  [2023-09-18 05:22:14.746] [debug] Auto batchsize: 256, time per chunk 0.36976 ms
  [2023-09-18 05:22:14.847] [debug] Auto batchsize: 320, time per chunk 0.30902082 ms
  [2023-09-18 05:22:14.945] [debug] Auto batchsize: 384, time per chunk 0.249376 ms
  [2023-09-18 05:22:15.052] [debug] Auto batchsize: 448, time per chunk 0.23329373 ms
  [2023-09-18 05:22:15.160] [debug] Auto batchsize: 512, time per chunk 0.206154 ms
  [2023-09-18 05:22:15.224] [debug] Auto batchsize: 576, time per chunk 0.10607645 ms
  [2023-09-18 05:22:15.286] [debug] Auto batchsize: 640, time per chunk 0.0964112 ms
  [2023-09-18 05:22:15.338] [debug] Auto batchsize: 704, time per chunk 0.07466037 ms
  [2023-09-18 05:22:15.392] [debug] Auto batchsize: 768, time per chunk 0.069936 ms
  [2023-09-18 05:22:15.412] [debug] - set batch size for cuda:2 to 768
  [2023-09-18 05:22:15.549] [debug] Auto batch size: GPU memory available: 62.906171392GB
  [2023-09-18 05:22:15.549] [debug] Auto batch size: testing up to 768 in steps of 64
  [2023-09-18 05:22:15.831] [debug] Auto batchsize: 64, time per chunk 4.4161077 ms
  [2023-09-18 05:22:15.874] [debug] Auto batchsize: 128, time per chunk 0.332352 ms
  [2023-09-18 05:22:15.917] [debug] Auto batchsize: 192, time per chunk 0.22218134 ms
  [2023-09-18 05:22:15.986] [debug] Auto batchsize: 256, time per chunk 0.272112 ms
  [2023-09-18 05:22:16.084] [debug] Auto batchsize: 320, time per chunk 0.2984096 ms
  [2023-09-18 05:22:16.183] [debug] Auto batchsize: 384, time per chunk 0.251232 ms
  [2023-09-18 05:22:16.291] [debug] Auto batchsize: 448, time per chunk 0.23530972 ms
  [2023-09-18 05:22:16.402] [debug] Auto batchsize: 512, time per chunk 0.211382 ms
  [2023-09-18 05:22:16.513] [debug] Auto batchsize: 576, time per chunk 0.18943466 ms
  [2023-09-18 05:22:16.626] [debug] Auto batchsize: 640, time per chunk 0.1713008 ms
  [2023-09-18 05:22:16.742] [debug] Auto batchsize: 704, time per chunk 0.16211344 ms
  [2023-09-18 05:22:16.828] [debug] Auto batchsize: 768, time per chunk 0.108972006 ms
  [2023-09-18 05:22:16.848] [debug] - set batch size for cuda:3 to 768
  [2023-09-18 05:22:16.848] [debug] - adjusted chunk size to match model stride: 10000 -> 9996
  [2023-09-18 05:22:16.848] [debug] - adjusted overlap to match model stride: 500 -> 498
  vbz_filter: compression error
  HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
    #000: ../../src/H5Dio.c line 179 in H5Dread(): can't read data
      major: Dataset
      minor: Read failed
    #001: ../../src/H5Dio.c line 547 in H5D__read(): can't read data
      major: Dataset
      minor: Read failed
    #002: ../../src/H5Dchunk.c line 1836 in H5D__chunk_read(): unable to read raw data chunk
      major: Low-level I/O
      minor: Read failed
    #003: ../../src/H5Dchunk.c line 2867 in H5D__chunk_lock(): data pipeline read failed
      major: Data filters
      minor: Filter operation failed
    #004: ../../src/H5Z.c line 1377 in H5Z_pipeline(): filter returned failure during read
      major: Data filters
      minor: Read failed
  [2023-09-18 05:36:45.498] [debug] Written 0 records.
  [2023-09-18 05:36:45.538] [error] Error during HDF5 Read:  

Work dir:
  /nfs/home/xyz/ABC/workspace/88/4ffe6bd86219b0d76fd6d882b32230

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (2)
```

**Comment by tijyojwad** [comment]
Hi @ymcki - could you convert the fast5 to pod5 and try again? And are you reading the data off local disk or a network drive?

pod5 is the recommended format for working with dorado. If there's an issue with one of the files the pod5 conversion we can dive into that separately.

**Comment by ymcki** [comment]
I am getting this error while converting. I am re-running without the problematic
fast5 according to the error message.

But what's going on here?

```
ERROR:pod5:Encountered an exception in /nfs/data/XXXXXX_1739_2A_XXXX_004fd8c6/fast5/XXXX_004fd8c6_ca94f4c4_16.fast5 - Can't read data (filter returned failure during read)
NoneType: None
ERROR:pod5:Trace Exception /nfs/data/XXXXXXX_739_2A_XXX_004fd8c6/fast5/XXXXXX_004fd8c6_ca94f4c4_16.fast5
Traceback (most recent call last):
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/pod5/tools/pod5_convert_from_fast5.py", line 668, in convert_fast5_files
    total_reads = convert_fast5_file(path, queues, signal_chunk_size)
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/pod5/tools/utils.py", line 184, in wrapper
    raise exc
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/pod5/tools/utils.py", line 181, in wrapper
    ret = func(*args, **kwargs)
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/pod5/tools/pod5_convert_from_fast5.py", line 625, in convert_fast5_file
    reads = convert_fast5_file_chunk(
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/pod5/tools/pod5_convert_from_fast5.py", line 608, in convert_fast5_file_chunk
    raise exc
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/pod5/tools/pod5_convert_from_fast5.py", line 602, in convert_fast5_file_chunk
    read = convert_fast5_read(f5_read, cache, signal_chunk_size)
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/pod5/tools/pod5_convert_from_fast5.py", line 540, in convert_fast5_read
    signal = raw["Signal"][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/nfs/home/miniconda3/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 768, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 376, in h5py._selector.Reader.read
OSError: Can't read data (filter returned failure during read)
NoneType: None
```

**Comment by tijyojwad** [comment]
```
signal = raw["Signal"][()]
``` 
this line leads me to think there's no data in this file or it's been corrupted somehow. did this file work before?

**Comment by ymcki** [comment]
Never worked for this file. So probably is just file corruption.
