### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by derekstein** [nanoporetech/dorado#41]
Hi, I have been trying to install dorado but am getting what I think is a dependancy error. This is what I am seeing ... I have a feeling it has to do with the depreciation of collections.Iterable to collections.abc.Iterable. However I am not sure how to fix this error!

Discarding https://files.pythonhosted.org/packages/4e/a6/4a1576e4a51b10b4b7440cbd36fc3c71fb69fb634672ce0725de614182ca/astropy-4.2.1.tar.gz (from https://pypi.org/simple/astropy/) (requires-python:>=3.7): Requested astropy from https://files.pythonhosted.org/packages/4e/a6/4a1576e4a51b10b4b7440cbd36fc3c71fb69fb634672ce0725de614182ca/astropy-4.2.1.tar.gz (from dorado) has inconsistent version: expected '4.2.1', but metadata has '0.0.0'
  Using cached astropy-4.2.tar.gz (7.5 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      Collecting setuptools
        Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
      Collecting setuptools_scm
        Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting cython==0.29.14
        Using cached Cython-0.29.14.tar.gz (2.1 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [50 lines of output]
            Unable to find pgen, not compiling formal grammar.
            running egg_info
            creating /private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-pip-egg-info-7eyq_j1r/Cython.egg-info
            writing /private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-pip-egg-info-7eyq_j1r/Cython.egg-info/PKG-INFO
            writing dependency_links to /private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-pip-egg-info-7eyq_j1r/Cython.egg-info/dependency_links.txt
            writing entry points to /private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-pip-egg-info-7eyq_j1r/Cython.egg-info/entry_points.txt
            writing top-level names to /private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-pip-egg-info-7eyq_j1r/Cython.egg-info/top_level.txt
            writing manifest file '/private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-pip-egg-info-7eyq_j1r/Cython.egg-info/SOURCES.txt'
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-install-zdwcc9d3/cython_306094b2917846c79bd3e0660c0a186f/setup.py", line 228, in <module>
                setup(
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
                return distutils.core.setup(**attrs)
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
                self.run_command(cmd)
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
                cmd_obj.run()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 308, in run
                self.find_sources()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
                mm.run()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 560, in run
                self.add_defaults()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
                sdist.add_defaults(self)
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
                super().add_defaults()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
                self._add_defaults_ext()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
                build_ext = self.get_finalized_command('build_ext')
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 306, in get_finalized_command
                cmd_obj.ensure_finalized()
              File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 109, in ensure_finalized
                self.finalize_options()
              File "/private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-install-zdwcc9d3/cython_306094b2917846c79bd3e0660c0a186f/Cython/Distutils/build_ext.py", line 20, in finalize_options
                self.distribution.ext_modules[:] = cythonize(
              File "/private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-install-zdwcc9d3/cython_306094b2917846c79bd3e0660c0a186f/Cython/Build/Dependencies.py", line 959, in cythonize
                module_list, module_metadata = create_extension_list(
              File "/private/var/folders/6s/23wxsrjj0pl5kyfs_57rjf7h0000gn/T/pip-install-zdwcc9d3/cython_306094b2917846c79bd3e0660c0a186f/Cython/Build/Dependencies.py", line 752, in create_extension_list
                elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
            AttributeError: module 'collections' has no attribute 'Iterable'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by vellamike** [comment]
You are trying to install the python astronomy-package [Dorado](https://dorado.readthedocs.io/en/stable/dorado/index.html) which is completely unrelated to the C++ Oxford Nanopore basecaller by the same name. Which package are you intending to install?
