### ISSUE TITLE
Error in Basecalling POD5 Skip File: "Invalid: null file passed to C API"

### ISSUE THREAD

**Issue by diego-taquiri** [nanoporetech/dorado#998]
I am encountering an issue with basecalling a POD5 skip file using Dorado. I have two POD5 skip files generated during a GridIon sequencing run with a P2 solo attached. These files were generated by pressing stop in Minknow after the sequencing finished but before the basecalling completed. One of the POD5 files (200 GB) was basecalled successfully, but the other file (300 GB) failed with the error:

[error] Failed to open file
[error] Failed to open file /path/pod5/PAY94502_skip_01051060_348da211_2.pod5: Invalid: null file passed to C API
[error] No POD5 or FAST5 reads found in path: /path/pod5

I expected both POD5 files to be basecalled without any issues. The failed POD5 file was generated under the same conditions as the successful one. I am unsure if the issue is related to file size, potential corruption, or another factor.

Run environment:

Dorado version: 0.7.3
Dorado command: dorado basecaller --emit-fastq --no-trim /path/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 /path/pod5 | gzip > /path/results/basecalled.fastq.gz
Operating system: Ubuntu 20.04
Hardware: GridIon
Source data type: POD5
Source data location: On-device storage

Logs

Here is the output trace from the Dorado run with increased verbosity:

[2024-08-22 10:28:59.494] [info] Running: "basecaller" "--emit-fastq" "--no-trim" "/data/programs/dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "/data/MAGICWANDS_LigV14/celda05_06082024_MW/20240806_2027_P2S-01119-A_PAY94502_01051060/pod5_skip_try3_bash/pod5"
[2024-08-22 10:28:59.515] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
[2024-08-22 10:28:59.520] [info] > Creating basecall pipeline
[2024-08-22 10:28:59.520] [error] Failed to open file /data/MAGICWANDS_LigV14/celda05_06082024_MW/20240806_2027_P2S-01119-A_PAY94502_01051060/pod5_skip_try3_bash/pod5/PAY94502_skip_01051060_348da211_2.pod5: Invalid: null file passed to C API
[2024-08-22 10:28:59.520] [error] No POD5 or FAST5 reads found in path: /data/MAGICWANDS_LigV14/celda05_06082024_MW/20240806_2027_P2S-01119-A_PAY94502_01051060/pod5_skip_try3_bash/pod5

Additional Logs

$ /data/programs/dorado-0.7.3-linux-x64/bin/dorado -vv
[2024-08-22 11:10:30.649] [info] Running: "-vv"
dorado:   0.7.3+6e6c45c+cu11080
libtorch: 2.0.0-ont
minimap2: 2.27-r1193

**Comment by HalfPhoton** [comment]
The pod5 file could be corrupted in some way - can you try to use the `pod5 recover` tool on this file to see if it's been corrupted?

**Comment by diego-taquiri** [comment]
> The pod5 file could be corrupted in some way - can you try to use the `pod5 recover` tool on this file to see if it's been corrupted?

thanks for the fast reply.

I tried pod5 recover and the pod5 skip file reduced a few gb in size. I tried one more time recover to see if any was missing:

 pod5 recover PAY94502_skip_01051060_348da211_2_recovered.pod5 
None of the 1 files given need recovery

However I still can't do the base calling of the recovered file:

[2024-08-23 15:18:53.110] [info] Running: "basecaller" "--kit-name" "SQK-NBD114-24" "--min-qscore" "8" "/data/programs/dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "/data/MAGICWANDS_LigV14/celda05_06082024_MW/20240806_2027_P2S-01119-A_PAY94502_01051060/pod5_skip_2_try4_recover/pod5_recovered/PAY94502_skip_01051060_348da211_2_recovered.pod5"
[2024-08-23 15:18:53.136] [info] > Creating basecall pipeline
[2024-08-23 15:18:53.137] [error] No POD5 or FAST5 reads found in path: /data/MAGICWANDS_LigV14/celda05_06082024_MW/20240806_2027_P2S-01119-A_PAY94502_01051060/pod5_skip_2_try4_recover/pod5_recovered/PAY94502_skip_01051060_348da211_2_recovered.pod5

**Comment by diego-taquiri** [comment]
this was the output of pod5 recover:

$ POD5_DEBUG=1 pod5 recover PAY94502_skip_01051060_348da211_2.pod5
PAY94502_skip_01051060_348da211_2_recovered.pod5 - Recovered
Recovered 39456080 signal rows, 0 reads, 0 run infos, 0 files with errors

but this new recovered file still can't be basecalled with the same error as before

 [error] No POD5 or FAST5 reads found in path: path/PAY94502_skip_01051060_348da211_2_recovered.pod5

**Comment by HalfPhoton** [comment]
Interesting - can you get any output from POD5 api?

Do you see any read ids from:

```pod5 view -IH | head```

**Comment by diego-taquiri** [comment]
> Interesting - can you get any output from POD5 api?
> 
> Do you see any read ids from:
> 
> `pod5 view -IH | head`

Apparently not, I got this error:

$ pod5 view -IH PAY94502_skip_01051060_348da211_2_recovered.pod5 | head

POD5 has encountered an error: 'Error while processing 'PAY94502_skip_01051060_348da211_2_recovered.pod5''

For detailed information set POD5_DEBUG=1'

The full error with  POD5_DEBUG=1 is this:

$ POD5_DEBUG=1 pod5 view -IH PAY94502_skip_01051060_348da211_2_recovered.pod5 | head
polars.exceptions.ColumnNotFoundError: not_set

Error originated just after this operation:
 WITH_COLUMNS:
 [String(PAY94502_skip_01051060_348da211_2_recovered.pod5).alias("filename"), col("read_id").bin.hex_encode().str.slice().str.concat_horizontal([String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice()]), col("well").alias("mux"), col("num_minknow_events").alias("minknow_events"), col("experiment_name").alias("experiment_id"), [(col("start")) / (col("sample_rate"))].alias("start_time"), [(col("num_samples")) / (col("sample_rate"))].alias("duration")]
  INNER JOIN:
  LEFT PLAN ON: [col("run_info")]
     WITH_COLUMNS:
     [col("run_info").strict_cast(String)]
      DF ["read_id", "read_number", "start", "median_before"]; PROJECT */20 COLUMNS; SELECTION: "None"
  RIGHT PLAN ON: [col("acquisition_id")]
    UNIQUE BY None
      UNIQUE BY None
        DF ["acquisition_id", "acquisition_start_time", "adc_max", "adc_min"]; PROJECT */18 COLUMNS; SELECTION: "None"
  END INNER JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: not_set

Error originated just after this operation:
 WITH_COLUMNS:
 [String(PAY94502_skip_01051060_348da211_2_recovered.pod5).alias("filename"), col("read_id").bin.hex_encode().str.slice().str.concat_horizontal([String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice()]), col("well").alias("mux"), col("num_minknow_events").alias("minknow_events"), col("experiment_name").alias("experiment_id"), [(col("start")) / (col("sample_rate"))].alias("start_time"), [(col("num_samples")) / (col("sample_rate"))].alias("duration")]
  INNER JOIN:
  LEFT PLAN ON: [col("run_info")]
     WITH_COLUMNS:
     [col("run_info").strict_cast(String)]
      DF ["read_id", "read_number", "start", "median_before"]; PROJECT */20 COLUMNS; SELECTION: "None"
  RIGHT PLAN ON: [col("acquisition_id")]
    UNIQUE BY None
      UNIQUE BY None
        DF ["acquisition_id", "acquisition_start_time", "adc_max", "adc_min"]; PROJECT */18 COLUMNS; SELECTION: "None"
  END INNER JOIN))
 WITH_COLUMNS:
 [String(PAY94502_skip_01051060_348da211_2_recovered.pod5).alias("filename"), col("read_id").bin.hex_encode().str.slice().str.concat_horizontal([String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice(), String(-), col("read_id").bin.hex_encode().str.slice()]), col("well").alias("mux"), col("num_minknow_events").alias("minknow_events"), col("experiment_name").alias("experiment_id"), [(col("start")) / (col("sample_rate"))].alias("start_time"), [(col("num_samples")) / (col("sample_rate"))].alias("duration")]
  INNER JOIN:
  LEFT PLAN ON: [col("run_info")]
     WITH_COLUMNS:
     [col("run_info").strict_cast(String)]
      DF ["read_id", "read_number", "start", "median_before"]; PROJECT */20 COLUMNS; SELECTION: "None"
  RIGHT PLAN ON: [col("acquisition_id")]
    UNIQUE BY None
      UNIQUE BY None
        DF ["acquisition_id", "acquisition_start_time", "adc_max", "adc_min"]; PROJECT */18 COLUMNS; SELECTION: "None"
  END INNER JOIN

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grid/.local/bin/pod5", line 8, in <module>
    sys.exit(main())
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/main.py", line 60, in main
    return run_tool(parser)
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/parsers.py", line 41, in run_tool
    raise exc
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/parsers.py", line 38, in run_tool
    return tool_func(**kwargs)
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/parsers.py", line 744, in run
    return view_pod5(**kwargs)
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/utils.py", line 63, in wrapper
    raise exc
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/utils.py", line 60, in wrapper
    ret = func(*args, **kwargs)
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/pod5_view.py", line 535, in view_pod5
    launch_view_workers(
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/pod5_view.py", line 489, in launch_view_workers
    join_workers(processes, exceptions_queue)
  File "/home/grid/.local/lib/python3.8/site-packages/pod5/tools/pod5_view.py", line 395, in join_workers
    raise RuntimeError(f"Error while processing '{path}'") from exc
RuntimeError: Error while processing 'PAY94502_skip_01051060_348da211_2_recovered.pod5'

**Comment by HalfPhoton** [comment]
This error indicates that the pod5 file you have is corrupt as it cannot load any read ids from the file.
